import { Batch, Product, Sale, Supplier, SummaryCard } from "@/lib/types";

export const summaryCards: SummaryCard[] = [
  { label: "Total products", value: "1,420", helper: "+24 this month" },
  { label: "Suppliers", value: "48", helper: "6 active this week" },
  { label: "Low stock", value: "19", helper: "Needs reorder planning" },
  { label: "Near expiry", value: "12", helper: "Within 30 days" },
];

export const suppliers: Supplier[] = [
  {
    id: 1,
    supplier_code: "SUP-001",
    name: "MediCore Distributors",
    contact_person: "Angela Cruz",
    phone: "+63 912 345 6789",
    email: "orders@medicore.example",
    address_line_1: "",
    address_line_2: "",
    city: "",
    state: "",
    postal_code: "",
    country: "",
    tax_id: "",
    payment_terms: "",
    notes: "",
    status: "active",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: 2,
    supplier_code: "SUP-002",
    name: "HealthFirst Supply",
    contact_person: "Noel Reyes",
    phone: "+63 917 222 4411",
    email: "support@healthfirst.example",
    address_line_1: "",
    address_line_2: "",
    city: "",
    state: "",
    postal_code: "",
    country: "",
    tax_id: "",
    payment_terms: "",
    notes: "",
    status: "active",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: 3,
    supplier_code: "SUP-003",
    name: "PrimeCare Wholesale",
    contact_person: "Lea Ramos",
    phone: "+63 918 555 1200",
    email: "sales@primecare.example",
    address_line_1: "",
    address_line_2: "",
    city: "",
    state: "",
    postal_code: "",
    country: "",
    tax_id: "",
    payment_terms: "",
    notes: "",
    status: "review",
    is_active: true,
    created_at: "",
    updated_at: "",
  },
];

export const products: Product[] = [
  {
    id: 1001,
    sku: "MED-001",
    barcode: "",
    generic_name: "Paracetamol",
    brand_name: "Biogesic",
    category_id: 1,
    category_name: "OTC Medicines",
    supplier_id: 1,
    supplier_name: "MediCore Distributors",
    classification: "branded",
    dosage_form: "",
    strength: "",
    manufacturer: "",
    unit: "tablet",
    description: "",
    cost_price: 5.0,
    selling_price: 8.5,
    tax_rate: 0,
    reorder_level: 100,
    max_stock_level: 1000,
    requires_prescription: false,
    is_active: true,
    stock_available: 560,
    created_at: "",
    updated_at: "",
  },
  {
    id: 1002,
    sku: "MED-002",
    barcode: "",
    generic_name: "Cetirizine",
    brand_name: "Allerkid",
    category_id: 2,
    category_name: "Prescription Medicines",
    supplier_id: 2,
    supplier_name: "HealthFirst Supply",
    classification: "generic",
    dosage_form: "",
    strength: "",
    manufacturer: "",
    unit: "tablet",
    description: "",
    cost_price: 9.0,
    selling_price: 12,
    tax_rate: 0,
    reorder_level: 80,
    max_stock_level: 500,
    requires_prescription: true,
    is_active: true,
    stock_available: 73,
    created_at: "",
    updated_at: "",
  },
  {
    id: 1003,
    sku: "SUP-101",
    barcode: "",
    generic_name: "Surgical Mask",
    brand_name: "SafeBreath",
    category_id: 3,
    category_name: "Medical Supplies",
    supplier_id: 3,
    supplier_name: "PrimeCare Wholesale",
    classification: "branded",
    dosage_form: "",
    strength: "",
    manufacturer: "",
    unit: "piece",
    description: "",
    cost_price: 2.1,
    selling_price: 6.25,
    tax_rate: 0,
    reorder_level: 250,
    max_stock_level: 5000,
    requires_prescription: false,
    is_active: true,
    stock_available: 180,
    created_at: "",
    updated_at: "",
  },
];

export const batches: Batch[] = [
  {
    id: 1,
    batch_number: "BATCH-24001",
    product_id: 1001,
    product_name: "Biogesic",
    supplier_id: 1,
    supplier_name: "MediCore Distributors",
    expiry_date: "2026-08-15",
    quantity_received: 500,
    quantity_available: 320,
    purchase_cost: 5.25,
    received_at: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: 2,
    batch_number: "BATCH-24002",
    product_id: 1002,
    product_name: "Allerkid",
    supplier_id: 2,
    supplier_name: "HealthFirst Supply",
    expiry_date: "2026-05-02",
    quantity_received: 100,
    quantity_available: 73,
    purchase_cost: 8.15,
    received_at: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: 3,
    batch_number: "BATCH-24003",
    product_id: 1003,
    product_name: "SafeBreath",
    supplier_id: 3,
    supplier_name: "PrimeCare Wholesale",
    expiry_date: "2027-01-30",
    quantity_received: 1000,
    quantity_available: 180,
    purchase_cost: 2.1,
    received_at: "",
    created_at: "",
    updated_at: "",
  },
];

export const sales: Sale[] = [
  {
    id: 1,
    sale_number: "SALE-20260409-001",
    sale_date: "2026-04-09",
    customer_id: null,
    customer_name: "",
    cashier_id: 1,
    cashier_name: "",
    customer_type: "walk-in",
    payment_method: "cash",
    payment_status: "paid",
    status: "completed",
    notes: "",
    gross_amount: 420,
    discount_amount: 20,
    tax_amount: 0,
    net_amount: 400,
    items: [],
    created_at: "",
    updated_at: "",
  },
  {
    id: 2,
    sale_number: "SALE-20260409-002",
    sale_date: "2026-04-09",
    customer_id: null,
    customer_name: "",
    cashier_id: 1,
    cashier_name: "",
    customer_type: "senior",
    payment_method: "cash",
    payment_status: "paid",
    status: "completed",
    notes: "",
    gross_amount: 760,
    discount_amount: 152,
    tax_amount: 0,
    net_amount: 608,
    items: [],
    created_at: "",
    updated_at: "",
  },
  {
    id: 3,
    sale_number: "SALE-20260409-003",
    sale_date: "2026-04-09",
    customer_id: null,
    customer_name: "",
    cashier_id: 1,
    cashier_name: "",
    customer_type: "pwd",
    payment_method: "cash",
    payment_status: "paid",
    status: "completed",
    notes: "",
    gross_amount: 1180,
    discount_amount: 236,
    tax_amount: 0,
    net_amount: 944,
    items: [],
    created_at: "",
    updated_at: "",
  },
];
